// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UepaMed.Infrastructure.Data;

#nullable disable

namespace UepaMed.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921202458_AdicionarOrigemImportacaoArquivo")]
    partial class AdicionarOrigemImportacaoArquivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UepaMed.Domain.Entities.Arquivos.ArquivoImportacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Origem")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeArtigos")
                        .HasColumnType("integer");

                    b.Property<int>("RevisaoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoArquivo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RevisaoId");

                    b.ToTable("ArquivosImportacao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Artigos.Artigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnoPublicacao")
                        .HasColumnType("integer");

                    b.Property<int>("ArquivoImportacaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Autores")
                        .HasColumnType("text");

                    b.Property<string>("DOI")
                        .HasColumnType("text");

                    b.Property<string>("Idioma")
                        .HasColumnType("text");

                    b.Property<int?>("MotivoExclusao")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("PMID")
                        .HasColumnType("text");

                    b.Property<string>("Paginas")
                        .HasColumnType("text");

                    b.Property<string>("Resumo")
                        .HasColumnType("text");

                    b.Property<int>("RevisaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Revista")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TipoPublicacao")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("Volume")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArquivoImportacaoId");

                    b.HasIndex("RevisaoId");

                    b.ToTable("Artigos");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Artigos.ConviteRevisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConvidadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Papel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RespondidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RevisaoId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioConvidadoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConvidadoPorUsuarioId");

                    b.HasIndex("UsuarioConvidadoId");

                    b.HasIndex("RevisaoId", "UsuarioConvidadoId", "Status");

                    b.ToTable("ConvitesRevisao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Artigos.DuplicidadeIgnorada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtigoAId")
                        .HasColumnType("integer");

                    b.Property<int>("ArtigoBId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataDecisao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RevisaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DuplicidadesIgnoradas");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Bibliotecas.ArquivoImportacaoBiblioteca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BibliotecaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantidadeArtigos")
                        .HasColumnType("integer");

                    b.Property<int>("TipoArquivo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BibliotecaId");

                    b.ToTable("ArquivosImportacaoBiblioteca");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Bibliotecas.ArtigoBiblioteca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnoPublicacao")
                        .HasColumnType("integer");

                    b.Property<int>("ArquivoImportacaoBibliotecaId")
                        .HasColumnType("integer");

                    b.Property<string>("Autores")
                        .HasColumnType("text");

                    b.Property<string>("DOI")
                        .HasColumnType("text");

                    b.Property<string>("Idioma")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("PMID")
                        .HasColumnType("text");

                    b.Property<string>("Paginas")
                        .HasColumnType("text");

                    b.Property<string>("Resumo")
                        .HasColumnType("text");

                    b.Property<string>("Revista")
                        .HasColumnType("text");

                    b.Property<string>("TipoPublicacao")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("Volume")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArquivoImportacaoBibliotecaId");

                    b.ToTable("ArtigosBiblioteca");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Bibliotecas.Biblioteca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Bibliotecas");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Planilhas.PlanilhaCelula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlanilhaColunaId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanilhaLinhaId")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.HasKey("Id");

                    b.HasIndex("PlanilhaColunaId");

                    b.HasIndex("PlanilhaLinhaId", "PlanilhaColunaId")
                        .IsUnique();

                    b.ToTable("PlanilhasCelula");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Planilhas.PlanilhaColuna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampoArtigoOrigem")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("PlanilhaRevisaoId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanilhaRevisaoId", "Ordem")
                        .IsUnique();

                    b.ToTable("PlanilhasColuna");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Planilhas.PlanilhaLinha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtigoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("PlanilhaRevisaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtigoId");

                    b.HasIndex("PlanilhaRevisaoId");

                    b.ToTable("PlanilhasLinha");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Planilhas.PlanilhaRevisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RevisaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RevisaoId")
                        .IsUnique();

                    b.ToTable("PlanilhasRevisao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Revisoes.Revisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CriteriosVotacao")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("Dominio")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Revisoes");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Revisoes.RevisaoMembro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Papel")
                        .HasColumnType("integer");

                    b.Property<int>("RevisaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RevisaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RevisoesMembro");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Votacoes.ConflitoVotacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtigoId")
                        .HasColumnType("integer");

                    b.Property<int?>("AvaliadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DecisaoFinal")
                        .HasColumnType("integer");

                    b.Property<int>("Motivo")
                        .HasColumnType("integer");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("boolean");

                    b.Property<int>("VotacaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtigoId");

                    b.HasIndex("VotacaoId", "ArtigoId")
                        .IsUnique();

                    b.ToTable("ConflitosVotacao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Votacoes.Votacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResponsavelConflitosUsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("RevisaoId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RevisaoId");

                    b.ToTable("Votacoes");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Votacoes.VotacaoArtigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtigoId")
                        .HasColumnType("integer");

                    b.Property<int>("VotacaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtigoId");

                    b.HasIndex("VotacaoId", "ArtigoId")
                        .IsUnique();

                    b.ToTable("VotacaoArtigos");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Votacoes.VotacaoParticipante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EhVotanteObrigatorio")
                        .HasColumnType("boolean");

                    b.Property<int>("Papel")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("VotacaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VotacaoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("VotacaoParticipantes");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Votacoes.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtigoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Opcao")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("VotacaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtigoId");

                    b.HasIndex("VotacaoId", "ArtigoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Arquivos.ArquivoImportacao", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Revisoes.Revisao", "Revisao")
                        .WithMany()
                        .HasForeignKey("RevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revisao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Artigos.Artigo", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Arquivos.ArquivoImportacao", "ArquivoImportacao")
                        .WithMany("Artigos")
                        .HasForeignKey("ArquivoImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UepaMed.Domain.Entities.Revisoes.Revisao", "Revisao")
                        .WithMany()
                        .HasForeignKey("RevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArquivoImportacao");

                    b.Navigation("Revisao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Artigos.ConviteRevisao", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Usuarios.Usuario", "ConvidadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("ConvidadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UepaMed.Domain.Entities.Revisoes.Revisao", "Revisao")
                        .WithMany()
                        .HasForeignKey("RevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UepaMed.Domain.Entities.Usuarios.Usuario", "UsuarioConvidado")
                        .WithMany()
                        .HasForeignKey("UsuarioConvidadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConvidadoPorUsuario");

                    b.Navigation("Revisao");

                    b.Navigation("UsuarioConvidado");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Bibliotecas.ArquivoImportacaoBiblioteca", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Bibliotecas.Biblioteca", "Biblioteca")
                        .WithMany("Importacoes")
                        .HasForeignKey("BibliotecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biblioteca");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Bibliotecas.ArtigoBiblioteca", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Bibliotecas.ArquivoImportacaoBiblioteca", "ArquivoImportacao")
                        .WithMany("Artigos")
                        .HasForeignKey("ArquivoImportacaoBibliotecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArquivoImportacao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Bibliotecas.Biblioteca", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Planilhas.PlanilhaCelula", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Planilhas.PlanilhaColuna", "Coluna")
                        .WithMany("Celulas")
                        .HasForeignKey("PlanilhaColunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UepaMed.Domain.Entities.Planilhas.PlanilhaLinha", "Linha")
                        .WithMany("Celulas")
                        .HasForeignKey("PlanilhaLinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coluna");

                    b.Navigation("Linha");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Planilhas.PlanilhaColuna", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Planilhas.PlanilhaRevisao", "Planilha")
                        .WithMany("Colunas")
                        .HasForeignKey("PlanilhaRevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planilha");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Planilhas.PlanilhaLinha", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Artigos.Artigo", "Artigo")
                        .WithMany()
                        .HasForeignKey("ArtigoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UepaMed.Domain.Entities.Planilhas.PlanilhaRevisao", "Planilha")
                        .WithMany("Linhas")
                        .HasForeignKey("PlanilhaRevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artigo");

                    b.Navigation("Planilha");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Planilhas.PlanilhaRevisao", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Revisoes.Revisao", "Revisao")
                        .WithMany()
                        .HasForeignKey("RevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revisao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Revisoes.Revisao", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Revisoes.RevisaoMembro", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Revisoes.Revisao", "Revisao")
                        .WithMany()
                        .HasForeignKey("RevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UepaMed.Domain.Entities.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revisao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Votacoes.ConflitoVotacao", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Artigos.Artigo", "Artigo")
                        .WithMany()
                        .HasForeignKey("ArtigoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UepaMed.Domain.Entities.Votacoes.Votacao", "Votacao")
                        .WithMany("Conflitos")
                        .HasForeignKey("VotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artigo");

                    b.Navigation("Votacao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Votacoes.Votacao", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Revisoes.Revisao", null)
                        .WithMany()
                        .HasForeignKey("RevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Votacoes.VotacaoArtigo", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Artigos.Artigo", "Artigo")
                        .WithMany()
                        .HasForeignKey("ArtigoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UepaMed.Domain.Entities.Votacoes.Votacao", "Votacao")
                        .WithMany("Artigos")
                        .HasForeignKey("VotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artigo");

                    b.Navigation("Votacao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Votacoes.VotacaoParticipante", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UepaMed.Domain.Entities.Votacoes.Votacao", "Votacao")
                        .WithMany("Participantes")
                        .HasForeignKey("VotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Votacao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Votacoes.Voto", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Artigos.Artigo", "Artigo")
                        .WithMany()
                        .HasForeignKey("ArtigoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UepaMed.Domain.Entities.Votacoes.Votacao", "Votacao")
                        .WithMany("Votos")
                        .HasForeignKey("VotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artigo");

                    b.Navigation("Votacao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Arquivos.ArquivoImportacao", b =>
                {
                    b.Navigation("Artigos");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Bibliotecas.ArquivoImportacaoBiblioteca", b =>
                {
                    b.Navigation("Artigos");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Bibliotecas.Biblioteca", b =>
                {
                    b.Navigation("Importacoes");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Planilhas.PlanilhaColuna", b =>
                {
                    b.Navigation("Celulas");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Planilhas.PlanilhaLinha", b =>
                {
                    b.Navigation("Celulas");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Planilhas.PlanilhaRevisao", b =>
                {
                    b.Navigation("Colunas");

                    b.Navigation("Linhas");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Votacoes.Votacao", b =>
                {
                    b.Navigation("Artigos");

                    b.Navigation("Conflitos");

                    b.Navigation("Participantes");

                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
